# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from baseten_python_sdk import Baseten

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        baseten = Baseten(
        
                        api_key_auth = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(baseten)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
