# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from baseten_python_sdk.pydantic.autoscaling_settings_v1 import AutoscalingSettingsV1
from baseten_python_sdk.pydantic.deployment_status_v1 import DeploymentStatusV1

class DeploymentV1(BaseModel):
    # Unique identifier of the deployment
    id: str = Field(alias='id')

    # Time the deployment was created in ISO 8601 format
    created_at: datetime = Field(alias='created_at')

    # Name of the deployment
    name: str = Field(alias='name')

    # Unique identifier of the model
    model_id_: str = Field(alias='model_id')

    # Whether the deployment is the production deployment of the model
    is_production: bool = Field(alias='is_production')

    # Whether the deployment is the development deployment of the model
    is_development: bool = Field(alias='is_development')

    # Status of the deployment
    status: DeploymentStatusV1 = Field(alias='status')

    # Number of active replicas
    active_replica_count: int = Field(alias='active_replica_count')

    # Autoscaling settings for the deployment
    autoscaling_settings: AutoscalingSettingsV1 = Field(alias='autoscaling_settings')
    class Config:
        arbitrary_types_allowed = True
