# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ModelV1(BaseModel):
    # Unique identifier of the model
    id: str = Field(alias='id')

    # Time the model was created in ISO 8601 format
    created_at: datetime = Field(alias='created_at')

    # Name of the model
    name: str = Field(alias='name')

    # Number of deployments of the model
    deployments_count: int = Field(alias='deployments_count')

    # Unique identifier of the production deployment of the model
    production_deployment_id: str = Field(alias='production_deployment_id')

    # Unique identifier of the development deployment of the model
    development_deployment_id: str = Field(alias='development_deployment_id')

    # Name of the instance type the model is deployed on
    instance_type_name: str = Field(alias='instance_type_name')
    class Config:
        arbitrary_types_allowed = True
