# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from baseten_python_sdk.pydantic.model_v1 import ModelV1

class ModelsV1(BaseModel):
    models: typing.List[ModelV1] = Field(alias='models')
    class Config:
        arbitrary_types_allowed = True
