# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class PromoteRequestV1(BaseModel):
    # Whether to scale down the previous production deployment after promoting
    scale_down_previous_production: typing.Optional[bool] = Field(None, alias='scale_down_previous_production')
    class Config:
        arbitrary_types_allowed = True
