# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class SecretV1(BaseModel):
    # Time the secret was created in ISO 8601 format
    created_at: datetime = Field(alias='created_at')

    # Name of the secret
    name: str = Field(alias='name')
    class Config:
        arbitrary_types_allowed = True
