# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from baseten_python_sdk.pydantic.secret_v1 import SecretV1

class SecretsV1(BaseModel):
    secrets: typing.List[SecretV1] = Field(alias='secrets')
    class Config:
        arbitrary_types_allowed = True
