# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import baseten_python_sdk
from baseten_python_sdk.model.update_autoscaling_settings_response_v1 import UpdateAutoscalingSettingsResponseV1
from baseten_python_sdk import configuration


class TestUpdateAutoscalingSettingsResponseV1(unittest.TestCase):
    """UpdateAutoscalingSettingsResponseV1 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
