# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import baseten_python_sdk
from baseten_python_sdk.model.deployments_v1 import DeploymentsV1
from baseten_python_sdk import configuration


class TestDeploymentsV1(unittest.TestCase):
    """DeploymentsV1 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
