# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from baseten_python_sdk import schemas  # noqa: F401


class PromoteRequestV1(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A request to promote a deployment to production.
    """


    class MetaOapg:
        
        class properties:
            scale_down_previous_production = schemas.BoolSchema
            __annotations__ = {
                "scale_down_previous_production": scale_down_previous_production,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scale_down_previous_production"]) -> MetaOapg.properties.scale_down_previous_production: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["scale_down_previous_production", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scale_down_previous_production"]) -> typing.Union[MetaOapg.properties.scale_down_previous_production, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["scale_down_previous_production", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        scale_down_previous_production: typing.Union[MetaOapg.properties.scale_down_previous_production, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PromoteRequestV1':
        return super().__new__(
            cls,
            *args,
            scale_down_previous_production=scale_down_previous_production,
            _configuration=_configuration,
            **kwargs,
        )
