# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from baseten_python_sdk import schemas  # noqa: F401


class UpdateAutoscalingSettingsV1(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A request to update autoscaling settings for a deployment. All fields are optional, and we only update ones passed in.
    """


    class MetaOapg:
        
        class properties:
            min_replica = schemas.IntSchema
            max_replica = schemas.IntSchema
            autoscaling_window = schemas.IntSchema
            scale_down_delay = schemas.IntSchema
            concurrency_target = schemas.IntSchema
            __annotations__ = {
                "min_replica": min_replica,
                "max_replica": max_replica,
                "autoscaling_window": autoscaling_window,
                "scale_down_delay": scale_down_delay,
                "concurrency_target": concurrency_target,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["min_replica"]) -> MetaOapg.properties.min_replica: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_replica"]) -> MetaOapg.properties.max_replica: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["autoscaling_window"]) -> MetaOapg.properties.autoscaling_window: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scale_down_delay"]) -> MetaOapg.properties.scale_down_delay: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["concurrency_target"]) -> MetaOapg.properties.concurrency_target: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["min_replica", "max_replica", "autoscaling_window", "scale_down_delay", "concurrency_target", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["min_replica"]) -> typing.Union[MetaOapg.properties.min_replica, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_replica"]) -> typing.Union[MetaOapg.properties.max_replica, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["autoscaling_window"]) -> typing.Union[MetaOapg.properties.autoscaling_window, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scale_down_delay"]) -> typing.Union[MetaOapg.properties.scale_down_delay, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["concurrency_target"]) -> typing.Union[MetaOapg.properties.concurrency_target, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["min_replica", "max_replica", "autoscaling_window", "scale_down_delay", "concurrency_target", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        min_replica: typing.Union[MetaOapg.properties.min_replica, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        max_replica: typing.Union[MetaOapg.properties.max_replica, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        autoscaling_window: typing.Union[MetaOapg.properties.autoscaling_window, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        scale_down_delay: typing.Union[MetaOapg.properties.scale_down_delay, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        concurrency_target: typing.Union[MetaOapg.properties.concurrency_target, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UpdateAutoscalingSettingsV1':
        return super().__new__(
            cls,
            *args,
            min_replica=min_replica,
            max_replica=max_replica,
            autoscaling_window=autoscaling_window,
            scale_down_delay=scale_down_delay,
            concurrency_target=concurrency_target,
            _configuration=_configuration,
            **kwargs,
        )
