# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from baseten_python_sdk.paths.v1_models_model_id_deployments_deployment_id_autoscaling_settings.patch import UpdateDeploymentSettingsRaw
from baseten_python_sdk.paths.v1_models_model_id_deployments_development_autoscaling_settings.patch import UpdateDevelopmentSettingRaw
from baseten_python_sdk.paths.v1_models_model_id_deployments_production_autoscaling_settings.patch import UpdateStatusRaw


class AutoscalingSettingApiRaw(
    UpdateDeploymentSettingsRaw,
    UpdateDevelopmentSettingRaw,
    UpdateStatusRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
