# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from baseten_python_sdk.paths.v1_models_model_id_deployments_deployment_id_autoscaling_settings.patch import UpdateDeploymentSettings
from baseten_python_sdk.paths.v1_models_model_id_deployments_development_autoscaling_settings.patch import UpdateDevelopmentSetting
from baseten_python_sdk.paths.v1_models_model_id_deployments_production_autoscaling_settings.patch import UpdateStatus
from baseten_python_sdk.apis.tags.autoscaling_setting_api_raw import AutoscalingSettingApiRaw


class AutoscalingSettingApi(
    UpdateDeploymentSettings,
    UpdateDevelopmentSetting,
    UpdateStatus,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AutoscalingSettingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AutoscalingSettingApiRaw(api_client)
