# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from baseten_python_sdk.paths.v1_models_model_id_deployments_deployment_id.get import DetailsGet
from baseten_python_sdk.paths.v1_models_model_id_deployments_development.get import GetDevelopmentDetails
from baseten_python_sdk.paths.v1_models_model_id_deployments_production.get import GetProductionDetails
from baseten_python_sdk.apis.tags.deployment_api_raw import DeploymentApiRaw


class DeploymentApi(
    DetailsGet,
    GetDevelopmentDetails,
    GetProductionDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DeploymentApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DeploymentApiRaw(api_client)
