# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from baseten_python_sdk.paths.v1_models_model_id_deployments_deployment_id.get import DetailsGetRaw
from baseten_python_sdk.paths.v1_models_model_id_deployments_development.get import GetDevelopmentDetailsRaw
from baseten_python_sdk.paths.v1_models_model_id_deployments_production.get import GetProductionDetailsRaw


class DeploymentApiRaw(
    DetailsGetRaw,
    GetDevelopmentDetailsRaw,
    GetProductionDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
