# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from baseten_python_sdk.paths.v1_models_model_id_deployments_development_promote.post import DeployPromoteRaw
from baseten_python_sdk.paths.v1_models_model_id_deployments_deployment_id_promote.post import DeploymentPromoteRaw
from baseten_python_sdk.paths.v1_models_model_id_deployments.get import GetAllDeploymentsRaw
from baseten_python_sdk.paths.v1_models.get import GetAllModelsRaw
from baseten_python_sdk.paths.v1_models_model_id.get import GetModelByIdRaw


class ModelApiRaw(
    DeployPromoteRaw,
    DeploymentPromoteRaw,
    GetAllDeploymentsRaw,
    GetAllModelsRaw,
    GetModelByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
