# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from baseten_python_sdk.paths.v1_secrets.get import GetAllSecrets
from baseten_python_sdk.paths.v1_secrets.post import UpsertNewSecret
from baseten_python_sdk.apis.tags.secret_api_raw import SecretApiRaw


class SecretApi(
    GetAllSecrets,
    UpsertNewSecret,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SecretApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SecretApiRaw(api_client)
