# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from baseten_python_sdk.type.autoscaling_settings_v1 import AutoscalingSettingsV1
from baseten_python_sdk.type.deployment_status_v1 import DeploymentStatusV1

class RequiredDeploymentV1(TypedDict):
    # Unique identifier of the deployment
    id: str

    # Time the deployment was created in ISO 8601 format
    created_at: datetime

    # Name of the deployment
    name: str

    # Unique identifier of the model
    model_id: str

    # Whether the deployment is the production deployment of the model
    is_production: bool

    # Whether the deployment is the development deployment of the model
    is_development: bool

    # Status of the deployment
    status: DeploymentStatusV1

    # Number of active replicas
    active_replica_count: int

    # Autoscaling settings for the deployment
    autoscaling_settings: AutoscalingSettingsV1

class OptionalDeploymentV1(TypedDict, total=False):
    pass

class DeploymentV1(RequiredDeploymentV1, OptionalDeploymentV1):
    pass
