# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from baseten_python_sdk.type.model_v1 import ModelV1

class RequiredModelsV1(TypedDict):
    models: typing.List[ModelV1]

class OptionalModelsV1(TypedDict, total=False):
    pass

class ModelsV1(RequiredModelsV1, OptionalModelsV1):
    pass
