# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPromoteRequestV1(TypedDict):
    pass

class OptionalPromoteRequestV1(TypedDict, total=False):
    # Whether to scale down the previous production deployment after promoting
    scale_down_previous_production: bool

class PromoteRequestV1(RequiredPromoteRequestV1, OptionalPromoteRequestV1):
    pass
