# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSecretV1(TypedDict):
    # Time the secret was created in ISO 8601 format
    created_at: datetime

    # Name of the secret
    name: str

class OptionalSecretV1(TypedDict, total=False):
    pass

class SecretV1(RequiredSecretV1, OptionalSecretV1):
    pass
