# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from baseten_python_sdk.type.update_autoscaling_settings_status_v1 import UpdateAutoscalingSettingsStatusV1

class RequiredUpdateAutoscalingSettingsResponseV1(TypedDict):
    # Status of the request to update autoscaling settings
    status: UpdateAutoscalingSettingsStatusV1

    # A message describing the status of the request to update autoscaling settings
    message: str

class OptionalUpdateAutoscalingSettingsResponseV1(TypedDict, total=False):
    pass

class UpdateAutoscalingSettingsResponseV1(RequiredUpdateAutoscalingSettingsResponseV1, OptionalUpdateAutoscalingSettingsResponseV1):
    pass
