# coding: utf-8

"""
    Baseten management API

    REST API for management of Baseten resources

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import baseten_python_sdk
from baseten_python_sdk.paths.v1_models_model_id_deployments_deployment_id_promote import post
from baseten_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1ModelsModelIdDeploymentsDeploymentIdPromote(ApiTestMixin, unittest.TestCase):
    """
    V1ModelsModelIdDeploymentsDeploymentIdPromote unit test stubs
        Promotes a deployment to production
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
